---
# tasks file for podman
- name: include default variables
  ansible.builtin.include_vars: "../vars/main.yml"

- name: include release specific variables
  ansible.builtin.include_vars: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
      skip: true

- name: include release specific tasks
  ansible.builtin.include_tasks: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
      skip: true

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create root directory if it does not exist
  ansible.builtin.file:
    path: "{{ share_root_directory }}"
    state: directory
    mode: '2775'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"


- name: Create systemd quadlet directory 
  ansible.builtin.file:
    path: "{{ quadlet_user_directory }}"
    state: directory
    mode: '751'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  

- name: systemctl start podman.service
  ansible.builtin.service:
    name: "podman.service"
    state: "started"
    enabled: true
  changed_when: false
  failed_when: false