apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  automountServiceAccountToken: false
  containers:
  - image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096
      hostPort: 8096
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /cache
      name: share-jellyfin-cache-host-0
    - mountPath: /config
      name: share-jellyfin-config-host-1
    - mountPath: /media
      name: share-media-host-2
  enableServiceLinks: false
  volumes:
  - hostPath:
      path: {{ jellyfin_cache }}
      type: Directory
    name: share-jellyfin-cache-host-0
  - hostPath:
      path: {{ jellyfin_config }}
      type: Directory
    name: share-jellyfin-config-host-1
  - hostPath:
      path: {{ media_directory }}
      type: Directory
    name: share-media-host-2